--- 
- name: Run tasks based on OS
  hosts: all 
  tasks: 
    - name: Group OS
      group_by: 
        key: "{{ ansible_distribution }}"
      
- hosts: CentOS
  become: yes
  become_user: root
  remote_user: centos
  tasks:
    - name: Install on centos 
      package: 
        name: telnet
        state: absent

- hosts: Amazon
  become: yes
  become_user: root
  remote_user: ec2-user
  tasks:
    - name: Install on ec2 
      package: 
        name: telnet

- hosts: Debian
  become: yes
  become_user: root
  remote_user: admin
  tasks:
    - name: Install on debian 
      package: 
        name: telnet