---
- name: Helps to download file
  hosts: all
  become: yes
  become_method: sudo
  vars_prompt:
    - name: URL
      prompt: "Give me the url: "
      private: no
  tasks:
    - name: Download 1 package
      get_url:
        url: "{{URL}}"
        dest: /tmp/