---
- name: Installs ncpa agent on instances
  hosts: all
  become: yes
  become_user: root 
  tasks: 
    - name: Create Repo on Centos6
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
      package: 
        name: "http://repo.nagios.com/nagios/6/nagios-repo-6-3.el6.noarch.rpm"
        state: latest
    
    - name: Install ncpa on centos 6
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
      package:
        name: ncpa
        state: present
      notify: NCPA_CENTOS_6
    
    - name: Change the code inside ncpa.cfg
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6" 
      lineinfile:
        path: /usr/local/ncpa/etc/ncpa.cfg
        regexp: "community_string = mytoken"
        line: "community_string = STRONGPASSWORD"



    - name: Create repo on centos 7 
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
      package: 
        name: "http://repo.nagios.com/nagios/7/nagios-repo-7-3.el7.noarch.rpm"
        state: latest

    - name: Install ncpa on centos 7
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
      package:
        name: ncpa
        state: present
      notify: NCPA_CENTOS_7

    - name: Change the code inside ncpa.cfg
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" 
      lineinfile:
        path: /usr/local/ncpa/etc/ncpa.cfg
        regexp: "community_string = mytoken"
        line: "community_string = STRONGPASSWORD"




    - name: Create repo on Amazon
      when: ansible_distribution == "Amazon"
      package: 
        name: "http://repo.nagios.com/nagios/7/nagios-repo-7-3.el7.noarch.rpm"
        state: latest

    - name: Install ncpa on Amazon
      when: ansible_distribution == "Amazon"
      package:
        name: ncpa
        state: present
      notify: NCPA_AMAZON

    - name: Change the code inside ncpa.cfg
      when: ansible_distribution == "Amazon"
      lineinfile:
        path: /usr/local/ncpa/etc/ncpa.cfg
        regexp: "community_string = mytoken"
        line: "community_string = STRONGPASSWORD"


  handlers:
    - name: NCPA_CENTOS_6
      service:
        name: ncpa_listener
        state: restarted

    - name: NCPA_CENTOS_7
      systemd:
        name: ncpa_listener
        state: restarted

    - name: NCPA_AMAZON
      systemd:
        name: ncpa_listener
        state: restarted
