---   #sudo pip install boto
- name: Creates ec2 instance
  hosts: localhost
  vars_files:
    - environment/prod_vars
  tasks:
    - name: Create instances
      ec2:
        key_name: "{{key_name}}"
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        region: "{{region}}"
        #user_data: "{{ lookup('file', 'user_data.sh') }}"