---
- name: Creates VPC
  hosts: localhost
  tasks:
    - ec2_vpc_net:
        name: dev
        state: present
        cidr_block: 10.0.0.0/16
        resource_tags: { "Environment":"Development" }
        region: us-east-1