---
# tasks file for r1soft
- block:
  - name: Created a Repository
    copy:
      src: r1soft.repo
      dest: /etc/yum.repos.d/r1soft.repo
  
  - name: Install r1soft agent
    package:
      name: serverbackup-enterprise-agent 
      state: present

  - name: Get key
    shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" 
  